### ISSUE TITLE
Scut links to Typesettings.io

### ISSUE THREAD

**Issue by silentiumsi** [elrumordelaluz/Sassisfaction#9]

**Comment by elrumordelaluz** [comment]
sorry @SimonMckeon, what do you mean?

**Comment by silentiumsi** [comment]
> {
>          "name": "Scut",
>          "url": "http://typesettings.io/",
>          "description": "A collection of Sass utilities to ease and improve our implementations of common style-code patterns.",
>          "tags": ["utilities", "patterns"]
>       },

I am happy to fix and issue a PR.

**Comment by elrumordelaluz** [comment]
You mean [this](https://github.com/elrumordelaluz/Sassisfaction/blob/gh-pages/sassisfaction.json#L318-L323) peace of code is wrong? 

You absolutely should issue a PR.

**Comment by silentiumsi** [comment]
Fixed in PR.

**Comment by elrumordelaluz** [comment]
merged, thanks @SimonMckeon
